//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCommons.Collections.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCommons.Collections.Resources.ExceptionStrings", typeof(ExceptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration has finished..
        /// </summary>
        internal static string Enumerator_EnumerationFinished {
            get {
                return ResourceManager.GetString("Enumerator_EnumerationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration has not been started yet. Call MoveNext() to start the enumeration..
        /// </summary>
        internal static string Enumerator_EnumerationHasNotStarted {
            get {
                return ResourceManager.GetString("Enumerator_EnumerationHasNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection has been changed. Enumeration with this enumerator is not possible anymore..
        /// </summary>
        internal static string Enumerator_MismatchingVersions {
            get {
                return ResourceManager.GetString("Enumerator_MismatchingVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection&apos;s capacity cannot be set to a negative value..
        /// </summary>
        internal static string Generic_NegativeCapacity {
            get {
                return ResourceManager.GetString("Generic_NegativeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peeking or removing elements is impossible, because the heap does not contain any items..
        /// </summary>
        internal static string Heap_PeekPopOnEmptyHeap {
            get {
                return ResourceManager.GetString("Heap_PeekPopOnEmptyHeap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying the collection is impossible while another collection change is being processed..
        /// </summary>
        internal static string PreviewingObservableCollection_CollectionChangingReentrancy {
            get {
                return ResourceManager.GetString("PreviewingObservableCollection_CollectionChangingReentrancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peeking or removing elements is impossible, because the priority queue does not contain any items..
        /// </summary>
        internal static string PriorityQueue_PeekDequeueOnEmptyHeap {
            get {
                return ResourceManager.GetString("PriorityQueue_PeekDequeueOnEmptyHeap", resourceCulture);
            }
        }
    }
}
