trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
